### ISSUE TITLE
IndexError when nonexist download is ordered to be deleted

### ISSUE THREAD

**Issue by EarlOfMagadan** [cyberrumor/ammo#12]
used the wrong number when deleting a mod from downloads, got this
`Skyrim Special Edition >_: delete download 9
Traceback (most recent call last):
  File "/home/jlak/Downloads/ammo/ammo/ammo.py", line 76, in <module>
    sys.exit(ui.repl())
  File "/home/jlak/Downloads/ammo/ammo/ui.py", line 407, in repl
    if not (ret := command["func"](*args)):
  File "/home/jlak/Downloads/ammo/ammo/controller.py", line 565, in delete
    name = self.downloads[index].name
IndexError: list index out of range
`

**Comment by cyberrumor** [comment]
Nice find, thank you for reporting :)

**Comment by cyberrumor** [comment]
Fixed in commit 455418e537815ef10d0027c06f620a6de14d4c41
