### ISSUE TITLE
Unable to install mod with apostrophe in the name

### ISSUE THREAD

**Issue by AsriFox** [cyberrumor/ammo#63]
When trying to install powerofthree's Tweaks, 7z command fails with the following errors:
```
 index | Download
-------|---------
[226]   powerofthree's Tweaks-51073-1-11-0-1722468545.7z
[342]   powerofthree's Tweaks-51073-1-12-2-1729660183.7z


Skyrim Special Edition >_: install 342
Verifying archive integrity...
sh: -c: line 1: unexpected EOF while looking for matching `''
[Errno 2] No such file or directory: '/home/asrifox/.local/share/ammo/Skyrim Special Edition/mods/powerofthrees_Tweaks5107311221729660183'
prepared_args=[<ammo.mod_controller.ModController object at 0x7a0bee5cad50>, 342]
Traceback (most recent call last):
  File "/home/asrifox/.local/bin/ammo", line 35, in <module>
    controller = GameController(args)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/asrifox/.local/share/pipx/venvs/ammo/lib/python3.12/site-packages/ammo/game_controller.py", line 129, in __init__
    self._manage_game(0)
  File "/home/asrifox/.local/share/pipx/venvs/ammo/lib/python3.12/site-packages/ammo/game_controller.py", line 201, in _manage_game
    ui.repl()
  File "/home/asrifox/.local/share/pipx/venvs/ammo/lib/python3.12/site-packages/ammo/ui.py", line 489, in repl
    command.func(*prepared_args)
  File "/home/asrifox/.local/share/pipx/venvs/ammo/lib/python3.12/site-packages/ammo/mod_controller.py", line 968, in install
    install_download(index, download)
  File "/home/asrifox/.local/share/pipx/venvs/ammo/lib/python3.12/site-packages/ammo/mod_controller.py", line 930, in install_download
    if has_extra_folder(extract_to):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asrifox/.local/share/pipx/venvs/ammo/lib/python3.12/site-packages/ammo/mod_controller.py", line 893, in has_extra_folder
    files = list(path.iterdir())
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1056, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/asrifox/.local/share/ammo/Skyrim Special Edition/mods/powerofthrees_Tweaks5107311221729660183'
```

The archive was downloaded from Nexus, and its name includes a single quote: `powerofthree's Tweaks-51073-1-12-2-1729660183.7z`. This must cause these three errors:
- [`subprocess.check_output(["7z", "t", f"{download.path}"`](https://github.com/cyberrumor/ammo/blob/7e0d9bf7c75077da5615effcb704e95062d603e7/ammo/mod_controller.py#L922):  
```
Verifying archive integrity...
sh: -c: line 1: unexpected EOF while looking for matching `''
```
- [`os.system(f"7z x '{download.location}' -o'{extract_to}'")`](https://github.com/cyberrumor/ammo/blob/7e0d9bf7c75077da5615effcb704e95062d603e7/ammo/mod_controller.py#L928):  
```
[Errno 2] No such file or directory: '/home/asrifox/.local/share/ammo/Skyrim Special Edition/mods/powerofthrees_Tweaks5107311221729660183'
```
- [`if has_extra_folder(extract_to):`](https://github.com/cyberrumor/ammo/blob/7e0d9bf7c75077da5615effcb704e95062d603e7/ammo/mod_controller.py#L930):  
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/asrifox/.local/share/ammo/Skyrim Special Edition/mods/powerofthrees_Tweaks5107311221729660183'
```

Maybe sanitization of paths will work; or these mods can be treated as exceptions and their archives can just be renamed automatically.

**Comment by cyberrumor** [comment]
I'll probably have to rename the archives. I've tried a bunch of shlex.quote magic but 7z CLI still isn't happy.

**Comment by cyberrumor** [comment]
Fixed in master. Thanks for the report.
